//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: streams.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol StreamsServicesendCall: ClientCallUnary {}

fileprivate final class StreamsServicesendCallBase: ClientCallUnaryBase<StreamsRequest, StreamsResponse>, StreamsServicesendCall {
  override class var method: String { return "/StreamsService/send" }
}


/// Instantiate StreamsServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol StreamsServiceService: ServiceClient {
  /// Synchronous. Unary.
  func send(_ request: StreamsRequest) throws -> StreamsResponse
  /// Asynchronous. Unary.
  func send(_ request: StreamsRequest, completion: @escaping (StreamsResponse?, CallResult) -> Void) throws -> StreamsServicesendCall

}

internal final class StreamsServiceServiceClient: ServiceClientBase, StreamsServiceService {
  /// Synchronous. Unary.
  internal func send(_ request: StreamsRequest) throws -> StreamsResponse {
    return try StreamsServicesendCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func send(_ request: StreamsRequest, completion: @escaping (StreamsResponse?, CallResult) -> Void) throws -> StreamsServicesendCall {
    return try StreamsServicesendCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol StreamsServiceProvider: ServiceProvider {
  func send(request: StreamsRequest, session: StreamsServicesendSession) throws -> StreamsResponse
}

extension StreamsServiceProvider {
  internal var serviceName: String { return "StreamsService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/StreamsService/send":
      return try StreamsServicesendSessionBase(
        handler: handler,
        providerBlock: { try self.send(request: $0, session: $1 as! StreamsServicesendSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol StreamsServicesendSession: ServerSessionUnary {}

fileprivate final class StreamsServicesendSessionBase: ServerSessionUnaryBase<StreamsRequest, StreamsResponse>, StreamsServicesendSession {}

